microservice-chart:
  namespace: "cittadini"

  image:
    repository: ghcr.io/pagopa/arpu-be
    pullPolicy: Always

  ingress:
    create: true
    path: /arcbe/(.*)

  livenessProbe:
    httpGet:
      path: /actuator/health/liveness
      port: 8080
    initialDelaySeconds: 60
    failureThreshold: 15
    periodSeconds: 10
    timeoutSeconds: 2

  readinessProbe:
    httpGet:
      path: /actuator/health/readiness
      port: 8080
    initialDelaySeconds: 60
    failureThreshold: 15
    periodSeconds: 10
    timeoutSeconds: 2

  deployment:
    create: true

  service:
    create: true
    type: ClusterIP
    port: 8080

  podAnnotations: {}

  podSecurityContext:
    seccompProfile:
      type: RuntimeDefault

  securityContext:
    allowPrivilegeEscalation: false
    runAsNonRoot: true
    runAsUser: 65534
    runAsGroup: 65534

  externalConfigMapFiles:
    create: true
    configMaps:
      - name: appinsights-config
        key: applicationinsights.json

  envConfig:
    APPLICATIONINSIGHTS_ROLE_NAME: "arpube"
    APPLICATIONINSIGHTS_INSTRUMENTATION_LOGGING_LEVEL: "OFF"
    APPLICATIONINSIGHTS_INSTRUMENTATION_MICROMETER_ENABLED: "false"
    APPLICATIONINSIGHTS_PREVIEW_PROFILER_ENABLED: "false"

    ENABLE_AUDIT_APPENDER: "TRUE"

    JWT_TOKEN_EXPIRATION_SECONDS: "28800"

    REDIS_PORT: "6380"
    REDIS_SSL_ENABLED: "true"

  externalConfigMapValues:
    rest-client:
      BIZ_EVENTS_PAID_NOTICE_BASE_URL: bizevents-paids-base-url
      PULL_PAYMENT_BASE_URL: pullpayment-base-url
      GPD_SERVICE_BASE_URL: gpd-service-base-url
      P4PA_AUTH_SERVER_BASE_URL: "http://p4pa-auth-microservice-chart:8080"
      P4PA_CITIZEN_SERVER_BASE_URL: "http://p4pa-citizen-microservice-chart:8080"
    assistance:
      ASSISTANCE_ZENDESK_PRODUCT_ID: assistance-arc-zendesk-product-id
      ASSISTANCE_ZENDESK_ORGANIZATION: assistance-arc-zendesk-organization
      HELP_CENTER_URL: arc-help-center-url
      ZENDESK_ACTION_URL: zendesk-action-url

  envSecret:
    APPLICATIONINSIGHTS_CONNECTION_STRING: appinsights-connection-string

    AUTH_CLIENT_ID: oneidentity-client-id
    AUTH_CLIENT_SECRET: oneidentity-client-secret
    # TODO redirect to new FE endpoint
    #AUTH_CLIENT_ID: oneidentity-arpu-client-id
    #AUTH_CLIENT_SECRET: oneidentity-arpu-client-secret

    JWT_TOKEN_PRIVATE_KEY: jwt-private-key
    JWT_TOKEN_PUBLIC_KEY: jwt-public-key

    REDIS_HOST: cache-standalone-host
    REDIS_PASSWORD: cache-password

    BIZ_EVENTS_PAID_NOTICE_SERVICE_API_KEY: pagopa-bizevents-paids-trx-apimv1-subscription-key
    PULL_PAYMENT_SERVICE_API_KEY: pagopa-pullpayment-apimv1-subscription-key
    GPD_SERVICE_API_KEY: pagopa-gpd-debt-positions-apimv1-subscription-key

    JWT_TOKEN_ASSISTANCE_ZENDESK_PRIVATE_KEY: jwt-assistance-zendesk-private-key

    WHITE_LIST_USERS: cf-whitelist

    P4PA_AUTH_CLIENT_SECRET: piattaforma-unitaria-client-secret

  # nodeSelector: {}

  tolerations:
    - key: "cittadiniOnly"
      operator: "Equal"
      value: "true"
      effect: "NoSchedule"
